# Use this file to control the main attributes of the website

# You
name: Sreeja Thummala

# Title for your site as it will appear in google
title: Resume for Sreeja Thummala

# SEO description
description: Resume for Sreeja Thummala.

# URL of this resume
url: 'https://sreejaThummala.github.io/JekyllResume'

# URL of your personal website (make same as URL if you don't have one)
personal: 'https:/sreejaThummala.github.io/JekyllResume'

# these should be pretty self-explanatory :-P
email: sthummala@wisc.edu

# Show this in the footer
copyright: All rights reserved.

# What should the navigation be called?
navigation: navigation

# Google analytics ID: UA-XXXXX-X
analytics: UA-9939917-25

# Jekyll assets gem
assets:
  dirname: assets
  baseurl: /assets/
  css_compressor: yui
  js_compressor: yui
  cachebust: hard
  cache: false
  gzip: nil # Cloudflare will do this
  sources:
    - _assets/javascripts
    - _assets/stylesheets

# Files in this repo that we don't want to go to the web
exclude: [
  'scss',
  '*.rb',
  '*.yml', 
  'vendor', 
  'Gemfile', 
  'Gemfile.lock',
  '*.sh',
  'README.md',
  'LICENSE.md',
]
